name = "StochasticPowerModelsTopologicalActions"
uuid = "1f2566fe-3671-4d03-bc3f-706c4b5b0fa2"
authors = ["Giacomo Bastianel"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
